name: Convert Python Script to Jupyter Notebook

on:
  workflow_dispatch:
    paths:
      - 'Training/Train-Phi3-4bit.py'

jobs:
  convert-to-notebook:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext

      # Convert Python script to Jupyter notebook
      - name: Convert script to notebook
        run: |
          jupytext --to notebook Training/Train-Phi3-4bit.py -o Training/Train-Phi3-4bit.ipynb

      # Commit and push the notebook if changes exist
      - name: Commit notebook
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Training/Train-Phi3-4bit.ipynb
          git diff --staged --quiet || git commit -m "Convert Train-Phi3-4bit.py to Jupyter notebook"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}