name: Run Python Script to Clone Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-clone-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for branch operations

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Run Python Script
        run: |
          python main.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create New Branch
        run: |
          BRANCH_NAME="update-repositories-$(date +%s)"
          git checkout -b $BRANCH_NAME

      - name: Add and Commit Cloned Repositories
        run: |
          git add .
          git commit -m "Add cloned repositories for Swift, Python, Lua, C, C++, Objective-C, C#, Ruby, JavaScript, TypeScript, Roblox, iOS, Flask, AI, Dylibs, IPA, and Files" || echo "No changes to commit"

      - name: Push New Branch
        run: |
          git push origin $(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update: Add Cloned Programming and Development Repositories"
          body: |
            This pull request adds cloned repositories for various programming languages and development tools, including:
            - Swift
            - Python
            - Lua
            - C
            - C++
            - Objective-C
            - C#
            - Ruby
            - JavaScript
            - TypeScript
            - Roblox
            - iOS
            - Flask
            - AI
            - Dylibs
            - IPA
            - Files

            The repositories are organized into respective directories by the main.py script. Please review the changes and merge if appropriate.
          branch: update-repositories-$(date +%s)
          base: main
          labels: enhancement
          assignees: ${{ github.actor }}